### ISSUE TITLE
the commandline for training the model on miniImageNet?

### ISSUE THREAD

**Issue by fikry102** [RongKaiWeskerMA/INSTA#1]
hello, how can I train this model on miniImageNet?
There were some "nan" errors when I tried to use the args of TieredImageNet to train the model on miniImageNet.

**Comment by RongKaiWeskerMA** [comment]
Hi, sorry for the late reply 
have you disabled the embedding optimization during training?  #82 line in INSTA_ProtoNet.py

**Comment by fikry102** [comment]
Thank you!
I ran it on TieredImageNet successfully after commenting out line 82.
I have another question: Which args should I modify if I want to run it on miniImageNet?
How about this one?【python train_fsl.py --max_epoch 200 --model_class INSTA_ProtoNet --backbone_class Res12 --dataset MiniImageNet--way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --balance_1 1 --temperature 64 --temperature2 64 --lr 0.0002 --lr_mul 30 --lr_scheduler cosine --step_size 20 --gamma 0.5 --gpu 0 --init_weights ./saves/initialization/miniImageNet/Res12-pre.pth --eval_interval 1 --use_euclidean】

**Comment by RongKaiWeskerMA** [comment]
Hi you can try to set the temperature to 24, temperatures 2 to 32 and lr_mul to 25
